# Generated by Django 5.0.7 on 2025-03-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('food_item_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sell_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.categories')),
            ],
        ),
    ]
