# Generated by Django 5.0.7 on 2025-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_categories_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, upload_to='food_items'),
        ),
    ]
