# Generated by Django 5.0.7 on 2025-03-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
