# Generated by Django 5.0.7 on 2025-03-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[(1, 'Open'), (2, 'Close')], max_length=10),
        ),
    ]
