# Generated by Django 5.0.7 on 2025-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, upload_to='food_items/'),
        ),
    ]
