# Generated by Django 5.0.7 on 2025-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_alter_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='food_item_name',
            field=models.CharField(max_length=100),
        ),
    ]
