# Generated by Django 5.0.7 on 2025-04-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_inventory_food_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=30)),
            ],
        ),
    ]
