# Generated by Django 5.0.7 on 2025-04-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_alter_customuser_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
