# Generated by Django 5.0.7 on 2025-04-09 18:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('supplier_company_Person', models.CharField(max_length=50)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('purchased_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('Done', 'Done'), ('Remaining', 'Remaining')], max_length=10)),
            ],
        ),
    ]
