# Generated by Django 5.0.7 on 2025-04-19 15:05

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_alter_purchase_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier_company_Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminside.supplier'),
        ),
    ]
