# Generated by Django 5.0.7 on 2025-04-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_supplier_alter_purchase_supplier_company_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier_company_Person',
            field=models.CharField(max_length=40),
        ),
    ]
