# Generated by Django 5.0.7 on 2025-04-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_alter_purchase_supplier_company_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminside.branch'),
        ),
    ]
