# Generated by Django 5.0.7 on 2025-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_alter_supplier_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
