# Generated by Django 5.0.7 on 2025-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_alter_supplier_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
