databases:
  - name: pos-db
    plan: free

services:
  - type: web
    name: pos-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pos-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: NVIDIA_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_ENDPOINT
        value: "https://api.smith.langchain.com"
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: "langsmith-demo"
