# Generated by Django 5.0.7 on 2025-03-30 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_id', models.IntegerField()),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('qunatity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffside.orders')),
            ],
        ),
    ]
