# Generated by Django 5.0.7 on 2025-03-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0002_orders_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
