# Generated by Django 5.0.7 on 2025-04-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_alter_customuser_image'),
        ('staffside', '0003_rename_qunatity_order_details_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('timeanddate', models.DateTimeField(null=True)),
                ('item_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='adminside.inventory')),
            ],
        ),
    ]
