# Generated by Django 5.0.7 on 2025-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0004_sales_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_report',
            name='item_name',
            field=models.CharField(max_length=30),
        ),
    ]
