# Generated by Django 5.0.7 on 2025-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0005_alter_sales_report_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('cust_name', models.CharField(max_length=50, null=True)),
                ('total_amount', models.IntegerField()),
                ('staff_name', models.CharField()),
                ('payment_method', models.CharField(max_length=20)),
                ('timeanddate', models.DateTimeField(null=True)),
            ],
        ),
    ]
