# Generated by Django 5.0.7 on 2025-04-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0007_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
